### ISSUE TITLE
ThreadsX.sum is not type inferable

### ISSUE THREAD

**Issue by mohamed82008** [tkf/ThreadsX.jl#182] opened 2021-11-14 15:44 UTC
Hi!

Thanks for this really nice package. I noticed that the `ThreadsX.sum` function can't be inferred properly in Julia 1.6.

```julia
julia> @code_warntype ThreadsX.sum(log, rand(100))
Variables
  #self#::Core.Const(ThreadsX.sum)
  f::Core.Const(log)
  itr::Vector{Float64}

Body::Any
1 ─ %1 = Core.NamedTuple()::Core.Const(NamedTuple())
│   %2 = Base.pairs(%1)::Core.Const(Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}())
│   %3 = ThreadsX.Implementations.:(var"#sum#14")(%2, #self#, f, itr)::Any
└──      return %3
```

**Comment by tkf** [comment] 2021-11-14 22:27
I think we can solve this in recent Julia. Let's track this issue in #166 since at the lowest layer it's the same issue.

duplication of #166

**Comment by tkf** [comment] 2021-11-14 22:28
duplicate of #166

**Closed by tkf** 2021-11-14 22:28 UTC
